---
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  flutter_hooks: ^0.17.0
  uuid: ^3.0.4
description: A new Flutter project.
dev_dependencies:
  build_runner: ^1.9.0
  flutter_test:
    sdk: flutter
environment:
  flutter: '>=1.17.0'
  sdk: '>=2.12.0 <3.0.0'
flutter:
  uses-material-design: true
name: todos
publish_to: none
version: 1.0.0+1